---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.kovo.li
  resources:
  - apigrouprequests
  - apiresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kovo.li
  resources:
  - apigrouprequests/finalizers
  - apiresourcedefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - api.kovo.li
  resources:
  - apigrouprequests/status
  - apiresourcedefinitions/status
  verbs:
  - get
  - patch
  - update
